"""empty message

Revision ID: e75211f3af71
Revises: 696485743e63
Create Date: 2020-02-19 18:30:35.471384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e75211f3af71'
down_revision = '696485743e63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shows',
    sa.Column('show_time', sa.DateTime(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('venue_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.ForeignKeyConstraint(['venue_id'], ['venues.id'], ),
    sa.PrimaryKeyConstraint('artist_id', 'venue_id')
    )
    op.drop_table('todos')
    op.add_column('artists', sa.Column('seeking_venues', sa.Boolean(), nullable=True))
    op.add_column('artists', sa.Column('seeking_venues_additional_message', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('website_link', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('genres', sa.ARRAY(sa.String()), nullable=True))
    op.add_column('venues', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    op.add_column('venues', sa.Column('seeking_talent_additional_message', sa.String(), nullable=True))
    op.add_column('venues', sa.Column('website_link', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venues', 'website_link')
    op.drop_column('venues', 'seeking_talent_additional_message')
    op.drop_column('venues', 'seeking_talent')
    op.drop_column('venues', 'genres')
    op.drop_column('artists', 'website_link')
    op.drop_column('artists', 'seeking_venues_additional_message')
    op.drop_column('artists', 'seeking_venues')
    op.create_table('todos',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('completed', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='todos_pkey')
    )
    op.drop_table('shows')
    # ### end Alembic commands ###
